#!/usr/bin/env bash
# shellcheck disable=SC2154,SC2086 # STD/colours come from install.func; $STD is word-split on purpose
#
# Runs inside the new container, started by ct/proxmox-portal.sh through
# community-scripts' build_container. PORTAL_* values are exported by the ct
# script; credentials are written from the host afterwards.

# Copyright (c) 2026 Nemer Tamimi
# License: MIT
# Source: https://github.com/nemerytamimi/proxmox-portal

# shellcheck source=/dev/null
source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

PORTAL_MODE="${PORTAL_MODE:-docker}"
PORTAL_IMAGE="${PORTAL_IMAGE:-ghcr.io/nemerytamimi/proxmox-portal}"
PORTAL_TAG="${PORTAL_TAG:-latest}"
PORTAL_REPO="${PORTAL_REPO:-https://github.com/nemerytamimi/proxmox-portal.git}"
PORTAL_REF="${PORTAL_REF:-main}"
PORTAL_TERRAFORM_VERSION="${PORTAL_TERRAFORM_VERSION:-1.16.4}"
DATA_DIR=/var/lib/proxmox-portal
APP_DIR=/opt/proxmox-portal

msg_info "Installing Dependencies"
$STD apt-get install -y curl ca-certificates openssl
msg_ok "Installed Dependencies"

# Proxmox applies mtu= only to the host side of the veth; the guest's eth0
# still comes up at 1500 and large TLS handshakes black-hole. It has to be an
# ifupdown hook: a systemd unit runs before ifupdown and the setting is lost.
if [[ -n "${PORTAL_MTU:-}" ]]; then
  msg_info "Pinning eth0 MTU to ${PORTAL_MTU}"
  cat <<EOF >/etc/network/if-up.d/zz-mtu
#!/bin/sh
[ "\$IFACE" = "eth0" ] || exit 0
ip link set dev eth0 mtu ${PORTAL_MTU}
EOF
  chmod +x /etc/network/if-up.d/zz-mtu
  ip link set dev eth0 mtu "${PORTAL_MTU}" || true
  msg_ok "Pinned eth0 MTU to ${PORTAL_MTU}"
fi

msg_info "Configuring ${DATA_DIR}"
mkdir -p "$DATA_DIR"/{workspaces,logs,plugin-cache,ssh}
chmod 700 "$DATA_DIR/ssh"
LOCAL_IP="${LOCAL_IP:-$(hostname -I | awk '{print $1}')}"
cat <<EOF >"$DATA_DIR/portal.env"
# Generated by the Proxmox Portal LXC script on $(date -u +%Y-%m-%dT%H:%M:%SZ). See .env.example.
DATABASE_URL="file:${DATA_DIR}/portal.db"
AUTH_SECRET="$(openssl rand -base64 32)"
AUTH_URL="http://${LOCAL_IP}:3000"
AUTH_TRUST_HOST="true"
APP_ENCRYPTION_KEY="$(openssl rand -base64 32)"

PVE_ENDPOINT="${PORTAL_PVE_ENDPOINT:-https://127.0.0.1:8006/}"
PVE_API_TOKEN=""
PVE_INSECURE="true"
PVE_SSH_USERNAME="root"
PVE_SSH_PRIVATE_KEY="${DATA_DIR}/ssh/terraform_pve"
PVE_NODE_ADDRESSES="${PORTAL_PVE_NODE_ADDRESSES:-}"

TERRAFORM_BIN="/usr/local/bin/terraform"
PORTAL_DATA_DIR="${DATA_DIR}"
TF_PLUGIN_CACHE_DIR="${DATA_DIR}/plugin-cache"
EOF
chmod 600 "$DATA_DIR/portal.env"
msg_ok "Configured ${DATA_DIR}"

if [[ "$PORTAL_MODE" == "docker" ]]; then
  msg_info "Installing Docker"
  $STD sh <(curl -fsSL https://get.docker.com)
  systemctl enable -q --now docker
  msg_ok "Installed Docker"

  # Keep in sync with compose.yml at the repo root. The data directory is a
  # bind mount at the same path as a native install, so backups and the docs
  # apply unchanged.
  msg_info "Starting ${PORTAL_IMAGE}:${PORTAL_TAG} (Patience)"
  mkdir -p "$APP_DIR"
  cat <<EOF >"$APP_DIR/compose.yml"
x-portal: &portal
  image: \${PORTAL_IMAGE}:\${PORTAL_TAG}
  env_file: ${DATA_DIR}/portal.env
  restart: unless-stopped
  volumes:
    - ${DATA_DIR}:${DATA_DIR}

services:
  web:
    <<: *portal
    command: ["web"]
    ports:
      - "3000:3000"

  worker:
    <<: *portal
    command: ["worker"]
    depends_on:
      web:
        condition: service_healthy
    stop_grace_period: 15m
EOF
  cat <<EOF >"$APP_DIR/.env"
PORTAL_IMAGE=${PORTAL_IMAGE}
PORTAL_TAG=${PORTAL_TAG}
EOF
  cd "$APP_DIR" || exit
  $STD docker compose pull
  if ! $STD docker compose up -d --wait --wait-timeout 180; then
    docker compose logs --tail 50 || true
    msg_error "Docker could not start the portal. If the logs mention AppArmor or 'permission denied' on sysctl/proc, Docker is blocked in this unprivileged LXC: re-run with PORTAL_MODE=native."
    exit 1
  fi
  msg_ok "Started ${PORTAL_IMAGE}:${PORTAL_TAG}"
else
  msg_info "Installing Node.js 24, Terraform ${PORTAL_TERRAFORM_VERSION} and tools"
  $STD apt-get install -y gnupg unzip sqlite3 openssh-client git
  if ! node --version 2>/dev/null | grep -q '^v24\.'; then
    $STD bash <(curl -fsSL https://deb.nodesource.com/setup_24.x)
    $STD apt-get install -y nodejs
  fi
  arch="$(dpkg --print-architecture)"
  base="https://releases.hashicorp.com/terraform/${PORTAL_TERRAFORM_VERSION}"
  zip="terraform_${PORTAL_TERRAFORM_VERSION}_linux_${arch}.zip"
  sums="terraform_${PORTAL_TERRAFORM_VERSION}_SHA256SUMS"
  cd /tmp || exit
  curl -fsSLO "$base/$zip"
  curl -fsSLO "$base/$sums"
  grep " ${zip}\$" "$sums" | sha256sum -c - >/dev/null
  $STD unzip -o "$zip" -d /usr/local/bin/
  rm -f "$zip" "$sums"
  msg_ok "Installed Node.js $(node --version), Terraform ${PORTAL_TERRAFORM_VERSION}"

  msg_info "Installing ${APP:-Proxmox Portal} from ${PORTAL_REF} (Patience)"
  $STD git clone --depth 1 --branch "$PORTAL_REF" "$PORTAL_REPO" "$APP_DIR"
  cd "$APP_DIR" || exit
  ln -sf "$DATA_DIR/portal.env" .env
  $STD npm ci --no-audit --no-fund
  $STD npx prisma db push --skip-generate
  $STD npm run build
  msg_ok "Installed ${APP:-Proxmox Portal}"

  msg_info "Creating Services"
  install -m644 deploy/proxmox-portal-web.service /etc/systemd/system/
  install -m644 deploy/proxmox-portal-worker.service /etc/systemd/system/
  systemctl daemon-reload
  systemctl enable -q --now proxmox-portal-web proxmox-portal-worker
  msg_ok "Created Services"
fi

motd_ssh
customize
cleanup_lxc
