import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { Guest, PveNode } from "@prisma/client";

import { env, paths } from "../env";

/**
 * Workspace generation.
 *
 * Every guest gets its own directory with its own state file. That isolation is
 * the point: a container whose apply is wedged cannot block anyone else's
 * order, and destroying it is a self-contained `terraform destroy` rather than
 * a surgical edit of a shared configuration.
 *
 * The generated `main.tf` is fixed per guest kind and never contains a value —
 * everything variable lives in `terraform.tfvars.json`, so a resize is a file
 * rewrite plus an apply, with no HCL templating to get wrong. Credentials are
 * not written to disk at all; the worker injects them as TF_VAR_* at spawn
 * time.
 */

/** Absolute path to the vendored modules, resolved from the app root. */
export function modulesDir(): string {
  return (
    process.env.PORTAL_MODULES_DIR ?? path.join(process.cwd(), "terraform", "modules")
  );
}

const PROVIDER_TF = `# Generated by the Proxmox portal. Do not edit by hand.

terraform {
  required_version = ">= 1.6"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.111"
    }
  }
}

variable "pve_endpoint" { type = string }
variable "pve_api_token" {
  type      = string
  sensitive = true
}
variable "pve_insecure" {
  type    = bool
  default = true
}
variable "pve_ssh_username" {
  type    = string
  default = "root"
}
variable "pve_ssh_private_key" { type = string }
variable "pve_node_addresses" {
  type    = map(string)
  default = {}
}

provider "proxmox" {
  endpoint  = var.pve_endpoint
  api_token = var.pve_api_token
  insecure  = var.pve_insecure

  ssh {
    agent       = false
    username    = var.pve_ssh_username
    private_key = file(var.pve_ssh_private_key)

    # The cluster is quorate over WireGuard, so the address the API reports for
    # a node is not always reachable from here. Pin them.
    dynamic "node" {
      for_each = var.pve_node_addresses
      content {
        name    = node.key
        address = node.value
      }
    }
  }
}
`;

function lxcMainTf(modules: string): string {
  return `# Generated by the Proxmox portal. Do not edit by hand.

variable "hostname" { type = string }
variable "node_name" { type = string }
variable "vm_id" { type = number }
variable "template_file_id" { type = string }
variable "os_type" { type = string }
variable "cores" { type = number }
variable "memory" { type = number }
variable "swap" { type = number }
variable "disk_size" { type = number }
variable "datastore_id" { type = string }
variable "bridge" { type = string }
variable "mtu" { type = number }
variable "ipv4_address" { type = string }
variable "ipv4_gateway" {
  type    = string
  default = null
}
variable "dns_servers" {
  type    = list(string)
  default = []
}
variable "ssh_public_keys" {
  type    = list(string)
  default = []
}
variable "root_password" {
  type      = string
  default   = null
  sensitive = true
}
variable "description" { type = string }
variable "tags" {
  type    = list(string)
  default = ["terraform", "portal"]
}

module "guest" {
  source = ${JSON.stringify(path.join(modules, "lxc"))}

  hostname  = var.hostname
  node_name = var.node_name
  vm_id     = var.vm_id

  template_file_id = var.template_file_id
  os_type          = var.os_type

  cores     = var.cores
  memory    = var.memory
  swap      = var.swap
  disk_size = var.disk_size

  datastore_id = var.datastore_id
  bridge       = var.bridge
  mtu          = var.mtu

  ipv4_address = var.ipv4_address
  ipv4_gateway = var.ipv4_gateway
  dns_servers  = var.dns_servers

  ssh_public_keys = var.ssh_public_keys
  root_password   = var.root_password

  # nesting only. Proxmox rejects keyctl/fuse for an API-token user with
  # HTTP 403 "only allowed for root@pam", so the portal never emits them.
  nesting = true

  description = var.description
  tags        = var.tags
}

output "vm_id" { value = module.guest.vm_id }
output "ipv4_address" { value = module.guest.ipv4_address }
output "node_name" { value = module.guest.node_name }
`;
}

function vmMainTf(modules: string): string {
  return `# Generated by the Proxmox portal. Do not edit by hand.

variable "hostname" { type = string }
variable "node_name" { type = string }
variable "vm_id" { type = number }
variable "cloud_image_file_id" {
  type    = string
  default = null
}
variable "clone_vm_id" {
  type    = number
  default = null
}
variable "iso_file_id" {
  type    = string
  default = null
}
variable "cores" { type = number }
variable "memory" { type = number }
variable "disk_size" { type = number }
variable "datastore_id" { type = string }
variable "bridge" { type = string }
variable "mtu" { type = number }
variable "ipv4_address" { type = string }
variable "ipv4_gateway" {
  type    = string
  default = null
}
variable "dns_servers" {
  type    = list(string)
  default = []
}
variable "ci_user" { type = string }
variable "ssh_public_keys" {
  type    = list(string)
  default = []
}
variable "ci_password" {
  type      = string
  default   = null
  sensitive = true
}
variable "description" { type = string }
variable "tags" {
  type    = list(string)
  default = ["terraform", "portal"]
}

module "guest" {
  source = ${JSON.stringify(path.join(modules, "vm"))}

  name      = var.hostname
  node_name = var.node_name
  vm_id     = var.vm_id

  cloud_image_file_id = var.cloud_image_file_id
  clone_vm_id         = var.clone_vm_id
  iso_file_id         = var.iso_file_id

  cores        = var.cores
  memory       = var.memory
  disk_size    = var.disk_size
  datastore_id = var.datastore_id

  bridge       = var.bridge
  mtu          = var.mtu
  ipv4_address = var.ipv4_address
  ipv4_gateway = var.ipv4_gateway
  dns_servers  = var.dns_servers

  ci_user         = var.ci_user
  ci_password     = var.ci_password
  ssh_public_keys = var.ssh_public_keys

  # Stock cloud images ship without qemu-guest-agent; leaving this on makes
  # every apply wait out the agent timeout before giving up.
  agent_enabled = false

  # A node change should move the VM, not rebuild it.
  migrate = true

  description = var.description
  tags        = var.tags
}

output "vm_id" { value = module.guest.vm_id }
output "ipv4_address" { value = var.ipv4_address }
output "node_name" { value = module.guest.node_name }
`;
}

/** The non-secret half of a workspace's inputs. */
export function tfvarsFor(
  guest: Guest,
  node: PveNode,
): Record<string, unknown> {
  const dns = node.dnsServers
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  const common = {
    hostname: guest.hostname,
    node_name: node.name,
    vm_id: guest.vmid,
    cores: guest.cores,
    memory: guest.memoryMb,
    disk_size: guest.diskGb,
    // The guest's own datastore, not the node's default. After a migration the
    // disk sits wherever PVE put it; handing Terraform the target node's
    // preferred storage instead would read as a storage change and force a
    // replacement, destroying the disk to "fix" it.
    datastore_id: guest.datastore || node.defaultDatastore,
    bridge: guest.bridge,
    mtu: guest.mtu,
    ipv4_address: guest.ipv4Address,
    ipv4_gateway: guest.ipv4Gateway,
    dns_servers: dns,
    ssh_public_keys: guest.sshPublicKey ? [guest.sshPublicKey.trim()] : [],
    description: `${guest.hostname} — ordered through the portal. Managed by Terraform.`,
    tags: ["terraform", "portal", guest.kind.toLowerCase()],
  };

  if (guest.kind === "LXC") {
    return {
      ...common,
      swap: guest.swapMb,
      template_file_id: guest.templateFileId,
      os_type: guest.osType,
    };
  }

  // Exactly one source reaches the module: an ISO install, a clone, or a
  // cloud image import.
  return {
    ...common,
    ci_user: guest.ciUser,
    cloud_image_file_id:
      guest.isoFileId || guest.cloneVmId ? null : guest.templateFileId,
    clone_vm_id: guest.isoFileId ? null : guest.cloneVmId,
    iso_file_id: guest.isoFileId,
  };
}

/**
 * Write (or rewrite) a guest's workspace. Safe to call repeatedly — a resize or
 * a migration is exactly this function plus another apply.
 */
export async function writeWorkspace(
  guest: Guest,
  node: PveNode,
): Promise<string> {
  const dir = paths.workspace(guest.id);
  await mkdir(dir, { recursive: true });

  const modules = modulesDir();
  await writeFile(path.join(dir, "provider.tf"), PROVIDER_TF, "utf8");
  await writeFile(
    path.join(dir, "main.tf"),
    guest.kind === "LXC" ? lxcMainTf(modules) : vmMainTf(modules),
    "utf8",
  );
  await writeFile(
    path.join(dir, "terraform.tfvars.json"),
    `${JSON.stringify(tfvarsFor(guest, node), null, 2)}\n`,
    "utf8",
  );

  return dir;
}

export async function ensureRuntimeDirs(): Promise<void> {
  await mkdir(paths.workspaces(), { recursive: true });
  await mkdir(paths.logs(), { recursive: true });
  await mkdir(env.pluginCacheDir, { recursive: true });
}
